16:31:31 -     INFO - wally           - All info would be stored into /var/wally_results/unmachinating_konner
16:31:31 -     INFO - wally           - Start discover_stage
16:31:31 -     INFO - wally           - Start reuse_vms_stage
16:31:31 -     INFO - wally           - Start log_nodes_statistic_stage
16:31:31 -     INFO - wally           - Found 1 nodes total
16:31:31 -    DEBUG - wally           - Found 1 nodes with role testnode
16:31:31 -     INFO - wally           - Start save_nodes_stage
16:31:31 -     INFO - wally           - Start connect_stage
16:31:31 -     INFO - wally           - Connecting to nodes
16:31:31 -     INFO - wally           - All nodes connected successfully
16:31:31 -     INFO - wally           - Start run_tests_stage
16:31:31 -    DEBUG - wally           - Run preparation
16:31:32 -    DEBUG - wally           - SSH:local Exec 'sudo apt-get -y install fio'
16:31:37 -     INFO - wally           - Prefilling file /tmp/test
16:31:37 -    DEBUG - wally           - SSH:local Exec 'sudo fio --name=xxx --filename=/tmp/test --direct=1 --bs=4m --size=20480m --rw=write'
16:32:46 -    ERROR - wally           - XXXX
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/io/fio.py", line 669, in pre_run_th
    self.prefill_test_files(rossh, files, force)
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/io/fio.py", line 554, in prefill_test_files
    rossh(cmd, timeout=curr_sz)
  File "/usr/local/lib/python2.7/dist-packages/wally/suits/itest.py", line 204, in closure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wally/ssh_utils.py", line 488, in run_over_ssh
    raise OSError(templ.format(node, cmd, proc.returncode, stdoutdata))
OSError: SSH:127.0.0.1 Cmd 'sudo fio --name=xxx --filename=/tmp/test --direct=1 --bs=4m --size=20480m --rw=write' failed with code -2. Output: xxx: (g=0): rw=write, bs=4M-4M/4M-4M/4M-4M, ioengine=sync, iodepth=1
fio-2.1.3
Starting 1 process
xxx: Laying out IO file(s) (1 file(s) / 20480MB)

fio: terminating on signal 2

xxx: (groupid=0, jobs=1): err= 0: pid=23212: Sat Jan 23 16:32:46 2016
  write: io=6732.0MB, bw=100448KB/s, iops=24, runt= 68628msec
    clat (msec): min=18, max=419, avg=40.21, stdev=23.19
     lat (msec): min=19, max=420, avg=40.76, stdev=23.19
    clat percentiles (msec):
     |  1.00th=[   23],  5.00th=[   26], 10.00th=[   31], 20.00th=[   33],
     | 30.00th=[   34], 40.00th=[   36], 50.00th=[   37], 60.00th=[   39],
     | 70.00th=[   41], 80.00th=[   45], 90.00th=[   50], 95.00th=[   56],
     | 99.00th=[  118], 99.50th=[  245], 99.90th=[  351], 99.95th=[  420],
     | 99.99th=[  420]
    bw (KB  /s): min=24188, max=128250, per=100.00%, avg=100945.04, stdev=17055.34
    lat (msec) : 20=0.24%, 50=91.09%, 100=7.55%, 250=0.77%, 500=0.36%
  cpu          : usr=1.45%, sys=2.53%, ctx=2338, majf=0, minf=9
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=1683/d=0, short=r=0/w=0/d=0

Run status group 0 (all jobs):
  WRITE: io=6732.0MB, aggrb=100448KB/s, minb=100448KB/s, maxb=100448KB/s, mint=68628msec, maxt=68628msec

Disk stats (read/write):
  sda: ios=0/1885, merge=0/10576, ticks=0/80044, in_queue=80048, util=97.06%

